version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
    groups:
      dbt:
        patterns:
          - "dbt-*"
      test-and-lint:
        patterns:
          - "pytest*"
          - "ruff*"
          - "mypy"
          - "pre-commit*"
          - "freezegun"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - github-actions
