services:
  mariadb-11-4:
    image: mariadb:11.4
    environment:
      MARIADB_ROOT_PASSWORD: ${DBT_MARIADB_PASSWORD}
    ports:
      - "${DBT_MARIADB_PORT:-3307}:3306"

  mariadb-11-8:
    image: mariadb:11.8
    environment:
      MARIADB_ROOT_PASSWORD: ${DBT_MARIADB_PASSWORD}
    ports:
      - "${DBT_MARIADB_118_PORT:-3308}:3306"

networks:
  default:
    name: dbt-mariadb-net
