[tox]
skipsdist = True
envlist = py313

[testenv:{unit,py313,py}]
description = unit testing
skip_install = true
passenv =
    DBT_*
    PYTEST_ADDOPTS
deps =
    -e.[test]
commands = {envpython} -m pytest {posargs} tests/unit

[testenv:{integration,py313,py}-mariadb]
description = adapter plugin integration testing
skip_install = true
passenv =
    DBT_*
    PYTEST_ADDOPTS
deps =
    -e.[test]
commands = {envpython} -m pytest -v {posargs} tests/functional
